export const recipeStampAbi = [
  {
    type: "function",
    name: "userSweets",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userSpicies",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "userFreshes",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSweets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSpicies",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalFreshes",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "stampSweet",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "stampSpicy",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "stampFresh",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "event",
    name: "SweetStamped",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userSweets", type: "uint256", indexed: false },
      { name: "totalSweets", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SpicyStamped",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userSpicies", type: "uint256", indexed: false },
      { name: "totalSpicies", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "FreshStamped",
    inputs: [
      { name: "user", type: "address", indexed: true },
      { name: "userFreshes", type: "uint256", indexed: false },
      { name: "totalFreshes", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
